### ISSUE TITLE
Terms&Conditions page layout is broken

### ISSUE THREAD

**Issue by laurawacrenier** [nicmarti/cfp-devoxx#212]
When accepting the Terms & Conditions for speakers, here is what I see:
<img width="1025" alt="Screenshot 2020-02-06 at 09 07 10" src="https://user-images.githubusercontent.com/11442948/73917826-80337c80-48c0-11ea-9b13-84dc0efce04c.png">
This is not very convenient for reading :) 
On Mac OS + FireFox 72.0.2

**Comment by aheritier** [comment]
whaouuuuu :-/

(that's why we have several sessions this year about the accessibility of web sites :-)

No better on Chrome :(

<img width="1675" alt="Screenshot 2020-02-06 09 35 49" src="https://user-images.githubusercontent.com/174600/73919638-35b3ff00-48c4-11ea-96f3-6bbda8fabdf7.png">


It's a problem due to the bootstrap upgrade

We completelely forgot that page

**Comment by aheritier** [comment]
PR in progress

**Comment by aheritier** [comment]
It should be better like this

![Screenshot 2020-02-06 09 43 44](https://user-images.githubusercontent.com/174600/73920238-47e26d00-48c5-11ea-91db-9294779dc4aa.png)

**Comment by aheritier** [comment]
PR #213 pushed. thx @laurawacrenier for reporting it

**Comment by aheritier** [comment]
cc @nicmarti @fcamblor

**Comment by laurawacrenier** [comment]
Wow that's efficient! Thank you team :)

**Comment by fcamblor** [comment]
It means a lot of speakers have (already) blindly accepted T&C ... lol
