### ISSUE TITLE
Login redirection broken

### ISSUE THREAD

**Issue by P4uline** [nicmarti/cfp-devoxx#214]
I'm on the reset password page to get my new password.

<img width="1130" alt="Capture d’écran 2020-02-07 à 09 11 57" src="https://user-images.githubusercontent.com/2003499/74012236-0962b600-498a-11ea-8ef4-bea7e22b691a.png">

Then click ```Continuer``` button, a 404 page shows up :

<img width="819" alt="Capture d’écran 2020-02-07 à 09 11 42" src="https://user-images.githubusercontent.com/2003499/74012261-17b0d200-498a-11ea-94ad-722406b9362d.png">

**Comment by aheritier** [comment]
Hi @P4uline 

Thx for reporting the issue. As far as I can see you were able to get a new access code thus it is only the button which isn't redirecting you to the homepage correctly
The culprit is here : https://github.com/nicmarti/cfp-devoxx/blob/f9b3e0e6a36218a55ed68d4e92135b5257a24bc2/app/views/Authentication/resetPassword.scala.html#L30

But I don't know very well this code, I will have to verify what is wrong (I don't see something obviously wrong) cc @nicmarti @fcamblor

**Comment by nicmarti** [comment]
Hmmm

It's on the server side in the Redirect, in the Authentication login
action.
There are 3 redirects. I will test with Pauline's profile on monday from
work (we work together)
Will keep you posted

Nicolas


Le ven. 7 févr. 2020 à 09:34, Arnaud Heritier <notifications@github.com> a
écrit :

**Comment by nicmarti** [comment]
Souci corrigé cette semaine
