### ISSUE TITLE
Incorrect eventName on the navigator tab

### ISSUE THREAD

**Issue by rverchere** [nicmarti/cfp-devoxx#333]
Hi!

A very little issue found on the devoxxfr2025.cfp.dev page. The eventName remains `{{eventName}}` on the navigator tab name:

![image](https://github.com/user-attachments/assets/3a5a366c-744a-449f-a7ec-867fe2760269)

**Comment by aheritier** [comment]
Hi @rverchere 
this bug tracker is for the previous version of the CFP.
Since last year we switched to a new version you can see the link to report a bug at the bottom right of the screen : https://gitlab.com/voxxed/cfp.dev/issues
The issue you see is this one : https://gitlab.com/voxxed/cfp.dev/-/issues/135
I tried to solve it a bit last year but it's not fully :( Angular + i18n aren't my friends.
I'll give another try....
